import { Space_Mono } from "next/font/google";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/Footer";
import NotificationProvider from "../components/ui/Notification";
import { UserProvider } from "../components/ui/UserContext";

import "./globals.css";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <NotificationProvider>
        <Navbar />
        <html lang="en" className={`${spaceMono.variable} h-full antialiased`}>
          <body className="min-h-full flex flex-col">{children}</body>
        </html>
        <Footer />
      </NotificationProvider>
    </UserProvider>
  );
}
